
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crudex?serverTimezone=Asia/Seoul
    username: java
    password:

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect